#!/bin/bash


export TERM=xterm-256color
#printf "\n"
printf "$(tput setaf 86)" #main text color

#uptime
upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh %02dm %02ds" "$days" "$hours" "$mins" "$secs"`
printf "  Uptime [$(tput setaf 155)${UPTIME}$(tput setaf 86)] by [$(date)]\n"

# local and wan IP
printf "  LAN: [$(tput setaf 40)$(ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/)$(tput setaf 86)] "
printf "  WAN: [$(tput setaf 40)$(wget -q -O - http://icanhazip.com/ | tail)$(tput setaf 86)]\n"

printf "$(tput sgr0)" #reset color
