#!/bin/bash
#
#    10-help-text - print the help text associated with the distro
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>,
#             Brian Murray <brian@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

export TERM=xterm-256color
#printf "\n"
printf "$(tput setaf 86)" #main text color

#uptime
upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh %02dm %02ds" "$days" "$hours" "$mins" "$secs"`
printf "  Uptime [$(tput setaf 155)${UPTIME}$(tput setaf 86)] by [$(date)]\n"

# local and wan IP
printf "  LAN: [$(tput setaf 40)$(ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/)$(tput setaf 86)] "
printf "  WAN: [$(tput setaf 40)$(wget -q -O - http://icanhazip.com/ | tail)$(tput setaf 86)]\n"

printf "$(tput sgr0)" #reset color
