#!/bin/bash
#

export TERM=xterm-256color
#printf "\n"
printf "$(tput setaf 86)" #main text color

#memory
memfree=$(cat /proc/meminfo | grep MemFree | awk {'print $2'})
memtotal=$(cat /proc/meminfo | grep MemTotal | awk {'print $2'})
memperc=$((100-${memfree}*100/${memtotal}))
membar=$(($memperc/2))

printf "  %-25s%27s\n" "Memory" "$((memfree/1024)) MB free"
printf "  ["

#bar color depending of free space
if [[ "$memperc" -lt "50" ]]
 then  printf "$(tput setaf 2)"
elif [[ "$memperc" -lt "70" ]]
 then printf "$(tput setaf 190)"
elif  [[ "$memperc" -lt "90" ]]
 then printf "$(tput setaf 178)"
else printf "$(tput setaf 202)"
fi

for i in $(seq 1 $membar)
 do
  printf "="
done
membar=$((50-$membar))
printf "$(tput setaf 240)"
for i in $(seq 1 $membar)
 do
  printf "="
done

printf "$(tput setaf 86)] $memperc%% "
printf "of $(($memtotal/1024)) MB\n"

printf "$(tput sgr0)" #reset color
