#!/bin/bash
#

bar () { #this will print the bar
membar=$(($1/2))
#bar color depending of free space
if [[ "$1" -lt "50" ]];
 then  printf "$(tput setaf 2)"
elif [[ "$1" -lt "70" ]];
 then printf "$(tput setaf 190)"
elif  [[ "$1" -lt "90" ]];
 then printf "$(tput setaf 178)"
else printf "$(tput setaf 202)"
fi

for i in $(seq 1 $membar)
 do
  printf "="
done
membar=$((50-$membar))
printf "$(tput setaf 240)"
for i in $(seq 1 $membar)
 do
  printf "="
done
}

#temp color function
export TERM=xterm-256color
#printf "\n"
printf "$(tput setaf 86)" #main text color

pool=$(zfs list | sed -n '2p' | awk {'print $1'})
poolused=$(zfs list | sed -n '2p' | awk {'print $2'})
poolused="${poolused//T}"
poolused="${poolused//.}"
poolused="${poolused//,}"
poolfree=$(zfs list | sed -n '2p' | awk {'print $3'})
#printf "  %-25s%27s\n" "$pool" "$poolfree TB free"
poolfree="${poolfree//T}"
printf "  %-25s%27s\n" "$pool" "$poolfree TB free"
poolfree="${poolfree//.}"
poolfree="${poolfree//,}"
pooltotal=$((${poolused}+${poolfree}))
poolperc=$((${poolused}*100/${pooltotal}))
pooltotal=$(echo "${pooltotal%??},${pooltotal: -2}")
printf "  [$(bar $poolperc)"
printf "$(tput setaf 86)] $poolperc%% of $pooltotal TB\n"

#zpool status
OUTPUT="$(zpool status -xv)"
printf "  ZPOOL Status: $(tput setaf 222)${OUTPUT}\n"

printf "$(tput sgr0)" #reset color
